# The majority of The Supplejack Manager code is Crown copyright (C) 2014, New Zealand Government,
# and is licensed under the GNU General Public License, version 3. Some components are 
# third party components that are licensed under the MIT license or otherwise publicly available. 
# See https://github.com/DigitalNZ/supplejack_manager for details. 

# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs. 
# http://digitalnz.org/supplejack

development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: harvester_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        # Change whether the session persists in safe mode by default.
        # (default: false)
        # safe: false

        # Change the default consistency model to :eventual or :strong.
        # :eventual will send reads to secondaries, :strong sends everything
        # to master. (default: :eventual)
        # consistency: :eventual

        # How many times Moped should attempt to retry an operation after
        # failure. (default: 30)
        # max_retries: 30

        # The time in seconds that Moped should wait before retrying an
        # operation on failure. (default: 1)
        # retry_interval: 1
    api:
      # database: dnz_api_development
      database: supplejack_api_development
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong
  # Configure Mongoid specific options. (optional)
  options:
    # Configuration for whether or not to allow access to fields that do
    # not have a field definition on the model. (default: true)
    # allow_dynamic_fields: true

    # Enable the identity map, needed for eager loading. (default: false)
    identity_map_enabled: true

    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serializaion. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Protect id and type from mass assignment. (default: true)
    # protect_sensitive_fields: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Skip the database version check, used when connecting to a db without
    # admin access. (default: false)
    # skip_version_check: false

    # User Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  sessions:
    default:
      database: harvester_test
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
    api:
      database: dnz_api_test
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

staging:
  sessions:
    default:
      database: harvester_staging
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    api:
      database: dnz_api_staging
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :strong

production:
  sessions:
    default:
      database: harvester_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
    api:
      database: dnz_api_production
      hosts:
        <%= ENV['API_MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
      options:
        consistency: :eventual
